openapi: 3.0.1

info:
  title: Todo API
  description: A simple service for managing todo lists.
  version: 0.1.0

servers:
  - url: https://todo.domain.tld

tags:
  - name: todo-list
  - name: todo-item

paths:

  /todo-list:
    get:
      tags:
        - todo-list
      summary: Get todo lists.
      description: Get all todo lists.
      responses:
        200:
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
    post:
      tags:
        - todo-list
      summary: Create todo list.
      description: Create a new todo list. 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
      responses:
        201:
          description: Item created.
          content: {}

  /todo-list/{todoListId}/todo-item:
    get:
      tags:
        - todo-item
      summary: Get todo items for list.
      description: Get all todo items for a specified todo list.
      parameters:
        - name: todoListId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful response.
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'

components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
    TodoItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        todoListId:
          type: integer
          format: int64
        name:
          type: string
        isComplete:
          type: boolean
          default: false
